### ISSUE TITLE
python data_source file_data.md 

### ISSUE THREAD

**Issue by beautifulpython** [zilliztech/arctern-docs#46]
branch : branch-0.1.x
doc : arctern-docs/doc-cn/source/python/data_source/file_data.md
```python
>>> import arctern
>>> import pandas as pd
>>> df = pd.read_csv("geos.csv",sep='|')
>>> df
   geos                                         
0  POINT (30 10)                                
1  POLYGON ((30 10, 40 40, 20 40, 10 20, 30 10))
2  POLYGON ((1 2, 3 4, 5 6, 1 2))               
3  POLYGON ((1 1, 3 1, 3 3, 1 3, 1 1)) 
>>> data = pd.Series(df['geos'].values,name='geos')
Traceback (most recent call last):
  File "/home/czp/anaconda3/envs/doc/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2646, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'geos'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/czp/anaconda3/envs/doc/lib/python3.7/site-packages/pandas/core/frame.py", line 2800, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/czp/anaconda3/envs/doc/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2648, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'geos'
>>> 





```

**Comment by beautifulpython** [comment]
The reason is that there are some Spaces in the CSV file, but the [] operator of pandas dataframe does not do the space filtering.

**Comment by become-nice** [comment]
> The reason is that there are some Spaces in the CSV file, but the [] operator of pandas dataframe does not do the space filtering.

I have delete extra space in docs, please retry it later. I have fix it in pr 90.
