### ISSUE TITLE
delete white space

### ISSUE THREAD

**Issue by beautifulpython** [zilliztech/arctern-docs#63]
https://arctern.io/docs/versions/v0.1.x/arctern-webdocs/development-doc-cn/html/spark/api/register/function/Register.html

https://arctern.io/docs/versions/v0.1.x/arctern-webdocs/development-doc-cn/html/spark/api/geospatial/function/geospatial/Spark_ST_Transform.html

```python
>>>  test_data = []
  File "<stdin>", line 1
    test_data = []
    ^
IndentationError: unexpected indent
>>> test_data.extend([('POINT (10 10)',)])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'test_data' is not defined
```

**Comment by beautifulpython** [comment]
PR https://github.com/zilliztech/arctern/pull/578 fix this issue.
