### ISSUE TITLE
ST_IsSimple api doc error

### ISSUE THREAD

**Issue by beautifulpython** [zilliztech/arctern-docs#65]
https://arctern.io/docs/versions/v0.1.x/arctern-webdocs/development-doc-cn/html/spark/api/geospatial/function/geospatial/Spark_ST_IsSimple.html

```python
>>> from pyspark.sql import SparkSession
>>> from arctern_pyspark import register_funcs
>>> spark_session = SparkSession.builder.appName("Python Arrow-in-Spark example").getOrCreate()
>>> register_funcs(spark_session)
>>> test_data = []
>>> test_data.extend([('POLYGON((1 2, 3 4, 5 6, 1 2))',)])
>>> test_data.extend([('LINESTRING(1 1,2 2,2 3.5,1 3,1 2,2 1)',)])
>>> test_data.extend([('POINT (1 1)')])
>>> simple_df = spark_session.createDataFrame(data=test_data, schema=['geos']).cache()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/czp/workspace/spark/python/pyspark/sql/session.py", line 787, in createDataFrame
    rdd, schema = self._createFromLocal(map(prepare, data), schema)
  File "/home/czp/workspace/spark/python/pyspark/sql/session.py", line 445, in _createFromLocal
    struct = self._inferSchemaFromList(data, names=schema)
  File "/home/czp/workspace/spark/python/pyspark/sql/session.py", line 377, in _inferSchemaFromList
    schema = reduce(_merge_type, (_infer_schema(row, names) for row in data))
  File "/home/czp/workspace/spark/python/pyspark/sql/session.py", line 377, in <genexpr>
    schema = reduce(_merge_type, (_infer_schema(row, names) for row in data))
  File "/home/czp/workspace/spark/python/pyspark/sql/types.py", line 1067, in _infer_schema
    raise TypeError("Can not infer schema for type: %s" % type(row))
TypeError: Can not infer schema for type: <class 'str'>
>>> 

```

**Comment by beautifulpython** [comment]
PR zilliztech/arctern#578 fix this issue.
