### ISSUE TITLE
offline_install_arctern_on_spark_cn.md

### ISSUE THREAD

**Issue by nezha2017** [zilliztech/arctern-docs#98]
I test it in docker container,  ubuntu:18.04
```bash
(arctern-spark) root@9c7f0c4d8505:~# python
Python 3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 23:03:20) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import arctern
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/miniconda3/envs/arctern-spark/lib/python3.7/site-packages/arctern/__init__.py", line 14, in <module>
    from ._wrapper_func import *
  File "/root/miniconda3/envs/arctern-spark/lib/python3.7/site-packages/arctern/_wrapper_func.py", line 63, in <module>
    from . import arctern_core_
ImportError: libGLU.so.1: cannot open shared object file: No such file or directory
>>> 
```

**Comment by czs007** [comment]
Some deb packages are required. I have pushed them to the offline branch of repo arctern-resources (https://github.com/zilliztech/arctern-resources).

Please retry it according to the installation document.
